# Generated by Django 4.0.2 on 2022-03-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kakao_nickname', models.CharField(max_length=20)),
                ('kakao_id', models.BigIntegerField(unique=True)),
                ('profile_image_url', models.URLField(max_length=1500)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
