# Generated by Django 4.0.3 on 2022-03-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_resume_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
